name: Build and package for windows

on:
  push:
    branches: [ "main", "CI-devel" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Single-Folder Application
      uses: fischerling/pyinstaller-action-windows@ace7c5f50489e38dbfb6651229207bba6e049ab4
      with:
        path: .

    - uses: actions/upload-artifact@v3
      with:
        name: quiz
        path: dist/windows
