name: Build and package for windows

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Package Application
      uses: fischerling/pyinstaller-action-windows@main
      with:
        path: .

    - uses: actions/upload-artifact@v3
      with:
        name: quiz
        path: dist/windows
